### ISSUE TITLE
Building on iOS causes "WebRTC/WebRTC.h file not found" (appearing in 0.9.2, works well in 0.9.1)

### ISSUE THREAD

**Issue by simonbengtsson** [flutter-webrtc/flutter-webrtc#1050]
Cannot build on iOS with `flutter build ipa` in 0.9.2. Its working well in 0.9.1 however.

```
Lexical or Preprocessor Issue (Xcode): 'WebRTC/WebRTC.h' file not found
```

I've tried both with and without the suggested solution [in the discussion](https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026) regarding this error.

**Workaround**
Simply specifying version 0.9.1 in pubspec.yaml works.

**Platform information**

* **Flutter version**: 3.0.5
* **Plugin version**: 0.9.2
* **OS**: iOS
* **OS version**: 15

**Comment by lamb1engcode** [comment]
The WebRTC.xframework compiled after the m104 release no longer supports iOS arm devices, so need to add the config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' to your ios/Podfile in your project

ios/Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
     target.build_configurations.each do |config|
      # Workaround for https://github.com/flutter/flutter/issues/64502
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' # <= this line
     end
  end
end

document webrtc update at version 0.9.2, hope useful for you!

**Comment by leeyisoft** [comment]
The answer to the issue is in Q&A - https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026.

**Comment by simonbengtsson** [comment]
I've tried adding the Q&A podfile snippet (and already using ONLY_ACTIVE_ARCH yes). After reinstalling pods I get the same issue. Does it work for you to build a release build with 0.9.2?

**Comment by simonbengtsson** [comment]
Basically. To reproduce this issue in 0.9.2

```
flutter create sample_project
cd sample_project
# Add post install hook below to `ios/Podfile`
flutter build ios # This will generate error below 
```

Post install hook used
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
        # Tried including both of these, either one and none of them with same error (ie WebRTC.h and RTCCVPixelBuffer.h file not found)
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = '$(inherited) i386'
    end
  end
end
```

Complete error
```
    /Users/simon/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.9.2/ios/Cla
    sses/FlutterWebRTCPlugin.m:1:
    /Users/simon/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.9.2/ios/Cla
    sses/FlutterWebRTCPlugin.h:8:9: fatal error: 'WebRTC/WebRTC.h' file not
    found
    #import <WebRTC/WebRTC.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/simon/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.9.2/ios/Cla
    sses/Broadcast/FlutterSocketConnectionFrameReader.m:10:9: fatal error:
    'WebRTC/RTCCVPixelBuffer.h' file not found
    #import <WebRTC/RTCCVPixelBuffer.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by leeyisoft** [comment]
> 0.9.2

I used flutter-webrtc 0.9.2 and the error "webrtc/webrtc. H file not found" was reported in the iOS simulator. Then I use the method of https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026,  no error

**Comment by leeyisoft** [comment]
Did you delete file ./ios/Podfile.lock and re-run it?

**Comment by leeyisoft** [comment]
Your code is different from this

"snippet begin ... snippet end "   ： 

`
#...
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # snippet begin
    if target.name == "WebRTC-SDK"
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = '$(inherited) i386'
      end
    end
    # snippet end
  end
end
`

**Comment by simonbengtsson** [comment]
To be 100% certain I tried all variants including the snippet above I now followed these steps and still get the error. Since it's a new project there was no Pods or Podfile.lock to delete.

```
flutter create sample_project
cd sample_project
flutter build ios # Succeeds
flutter pub add flutter_webrtc
# Uncomment "platform :ios, '9.0'" at the top of ios/Podfile and change to "platform :ios, '10.0'"
# Add post install hook (below) to ios/Podfile
flutter build ios
```

Post install hook used
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # snippet begin
    if target.name == "WebRTC-SDK"
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = '$(inherited) i386'
      end
    end
    # snippet end
  end
end
```

**Comment by leeyisoft** [comment]
> To be 100% certain I tried all variants including the snippet above I now followed these steps and still get the error. Since it's a new project there was no Pods or Podfile.lock to delete.
> 
> ```
> flutter create sample_project
> cd sample_project
> flutter build ios # Succeeds
> flutter pub add flutter_webrtc
> # Uncomment "platform :ios, '9.0'" at the top of ios/Podfile and change to "platform :ios, '10.0'"
> # Add post install hook (below) to ios/Podfile
> flutter build ios # Fails
> ```
> 
> Post install hook used
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     # snippet begin
>     if target.name == "WebRTC-SDK"
>       target.build_configurations.each do |build_configuration|
>         build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = '$(inherited) i386'
>       end
>     end
>     # snippet end
>   end
> end
> ```

That would be weird. Try it the following way, okay?

```
flutter clean
rm -rf ~/workspace/flutter/.pub-cache
rm -rf ~/.pub-cache
rm -rf ~/workspace/flutter/bin/cache 
flutter channel stable
flutter pub get
```

**Comment by leeyisoft** [comment]
That would be weird. Try it the following way, okay?

```
flutter clean
rm -rf ~/workspace/flutter/.pub-cache
rm -rf ~/.pub-cache
rm -rf ~/workspace/flutter/bin/cache 
flutter channel stable
flutter pub get
```

**Comment by simonbengtsson** [comment]
> flutter clean
> rm -rf ~/workspace/flutter/.pub-cache
> rm -rf ~/.pub-cache
> rm -rf ~/workspace/flutter/bin/cache 
> flutter channel stable
> flutter pub get

Same issue after following those steps. Just to confirm. Does it work for you to execute those steps?

```
flutter create sample_project
cd sample_project
flutter pub add flutter_webrtc
# Uncomment "platform :ios, '9.0'" at the top of ios/Podfile and change to "platform :ios, '10.0'"
# Add post install hook (above) to ios/Podfile
flutter build ios # Fails
```

**Comment by simonbengtsson** [comment]
Hmm, I am able to build after setting the entire project to arm64 only (removing armv7). Not ideal though since it doesn't work on simulators.

<img width="825" alt="Screen Shot 2022-08-11 at 11 36 28" src="https://user-images.githubusercontent.com/3586691/184105533-cdb65c33-9d43-4fd3-a5d8-cb960f900d6a.png">

**Comment by leeyisoft** [comment]
> > flutter clean 
> > rm -rf ~/workspace/flutter/.pub-cache 
> > rm -rf ~/.pub-cache 
> > rm -rf ~/workspace/flutter/bin/cache 
> > flutter channel stable 
> > flutter pub get
> 
> 遵循这些步骤后同样的问题。只是为了确认。执行这些步骤对您有用吗？
> 
> ```
> flutter create sample_project
> cd sample_project
> flutter pub add flutter_webrtc
> # Uncomment "platform :ios, '9.0'" at the top of ios/Podfile and change to "platform :ios, '10.0'"
> # Add post install hook (above) to ios/Podfile
> flutter build ios # Fails
> ```

Like when something goes wrong with my phone, I reboot it; I just undeveloped my APP, and when I get stuck, I try this

When encounter this problem, by the https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026 tip configuration, delete the file ./ios/Podfile.lock, A re-run should fix the problem

**Comment by simonbengtsson** [comment]
That seem to have been a fix for pre 0.9.2 but at least for me it doesn't work anymore. Would love to know it still works for other people though.

**Comment by leeyisoft** [comment]
The method https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026  is feasible on my computer, my code is here, I don't know if it is useful for you(to see my code, I need to switch to dev branch)

https://github.com/imboy-pub/imboy-flutter/blob/dev/pubspec.yaml

My PC environment ： 

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.8 20G730 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/leeyi/workspace/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 周前), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/leeyi/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.8 20G730 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by leeyisoft** [comment]
I had the same problem（iOS error: 'WebRTC/WebRTC.h' file not found） in the iOS emulator and solved it with the method https://github.com/flutter-webrtc/flutter-webrtc/discussions/1026;

When debugging the iPhone7 today, I still have this problem（iOS error: 'WebRTC/WebRTC.h' file not found）


flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.8 20G730 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/leeyi/workspace/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 周前), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/leeyi/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • iPhone7 (mobile) • 064cedc7fa15dc1353e8a45ab54655f10eeb5a1a • ios            • iOS 15.6 19G71
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 11.6.8
      20G730 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome
      103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by leeyisoft** [comment]
After relying on flutter_webrtc: ^0.9.3 a few hours ago, I used the following method to successfully debug the iPhone7 real machine (this is my project https://github.com/imboy-pub/imboy-flutter/tree/dev )


method from https://github.com/flutter-webrtc/flutter-webrtc/issues/713
```
You can fix this issue by doing these following steps:

Delete ios folder
Go to your project directory in terminal and run these commands
flutter create -i objc .
flutter clean && flutter pub get
cd ios
arch -x86_64 pod update
arch -x86_64 pod install
then at the top of your Pod file, paste this line platform :ios, '10.0'
right click on ios folder and open in xcode and then set all deployment target to 10
IMPORTANT: I think webrtc is not working on IOS simulator. I'm not sure. Your can run on real device.
```
