### ISSUE TITLE
Upgrade the lib to 0.5.7 occurs   java.lang.NoSuchMethodError: No virtual method createAudioDeviceModule

### ISSUE THREAD

**Issue by kklldog** [flutter-webrtc/flutter-webrtc#442]
when i upgrade the lib to 0.5.7 , it occurs a error . It looks like the org.webrtc lib have no createAudioDeviceModule method .
some one help me ?   
2020-12-29 16:55:02.522 5894-5894/com.md.hc.terminal E/org.webrtc.Logging: JavaAudioDeviceModule: HW AEC not supported
2020-12-29 16:55:02.522 5894-5894/com.md.hc.terminal E/org.webrtc.Logging: JavaAudioDeviceModule: HW NS not supported
2020-12-29 16:55:02.524 5894-5894/com.md.hc.terminal E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: No virtual method createAudioDeviceModule()Lorg/webrtc/audio/JavaAudioDeviceModule; in class Lorg/webrtc/audio/JavaAudioDeviceModule$Builder; or its super classes (declaration of 'org.webrtc.audio.JavaAudioDeviceModule$Builder' appears in /data/app/com.md.hc.terminal-2/base.apk:classes3.dex)
        at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(MethodCallHandlerImpl.java:153)
        at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:167)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2020-12-29 16:55:02.524 5894-5894/com.md.hc.terminal A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
